# Generated by Django 5.0.6 on 2024-05-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="nome",
            new_name="nome_completo",
        ),
    ]
