# Generated by Django 5.0.6 on 2024-05-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_nome_funcionario_nome_completo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=45)),
                ("horario_entrada", models.DateTimeField()),
                ("horario_saida", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Funcionario",
        ),
    ]
