# Generated by Django 5.0.6 on 2024-05-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_funcionarios_delete_funcionario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionarios",
            name="id",
        ),
        migrations.AlterField(
            model_name="funcionarios",
            name="nome_completo",
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
