# Generated by Django 5.0.6 on 2024-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_funcionarios_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionarios",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="funcionarios",
            name="nome_completo",
            field=models.CharField(max_length=45),
        ),
    ]
