# Generated by Django 5.0.6 on 2024-05-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_funcionarios_id_alter_funcionarios_nome_completo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionarios",
            name="id",
        ),
        migrations.AddField(
            model_name="funcionarios",
            name="codigo_funcionario",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
